### ISSUE TITLE
Too many ammessages values

### ISSUE THREAD

**Issue by Huji** [ricordisamoa/dewkin#11]
This failed: https://tools.wmflabs.org/dewkin/%DA%A9%D9%88%D8%B1%D9%88%D8%B4_%D8%AA%D9%87%D8%B1%D8%A7%D9%86%DB%8C@fawiki

Looking at the console log, the error message returned was: 
```
"error":{
  "code":"too-many-ammessages",
  "info":"Too many values supplied for parameter \"ammessages\". The limit is 50."
}
```

And the request sent  indeed had too many values for the ammesage parameter (to be exact, 51 items):

```

ammessages: ago|just-now|seconds|duration-seconds|minutes|hours|days|weeks|months|years|and|comma-separator|colon-separator|word-separator|parentheses|percent|diff|nchanges|size-bytes|tags-hitcount|Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sun|Mon|Tue|Wed|Thu|Fri|Sat|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|group-uploader-member|group-extendedconfirmed-member|group-autopatrolled-member|group-rollbacker-member|group-patroller-member
```

I think this is happening because the user is in multiple groups.

**Comment by ricordisamoa** [comment]
Nice catch! Edge-case reports like this one are especially valuable...
It should now work with users in arbitrarily large numbers of groups.

**Comment by ricordisamoa** [comment]
@Huji can you confirm it's fixed? Thanks in advance.

**Comment by Huji** [comment]
Yes. Thanks!
